[package]
name = "pwgen_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = { version = "0.6.0", package = "libadwaita", features = ["v1_5"] }
egui = "0.27.2"
egui_winit_platform = "0.22.0"
gtk = { version = "0.8.2", package = "gtk4" }
rand = "0.8.5"
winit = "0.30.0"
